### PR TITLE
Using waitSecondsIfNoQueue to save CPU

### PR DESCRIPTION
**Pull request by madeadi**
The example in README to use waitSecondsIfNoQueue is wrong. This pull request fixes the README.

### CODE REVIEW

**Comment by TonisOrmisson** [comment]
It's not "wrong"

It is just ab example of an optional setting. The default value is 0 meaning there is constant loop without delays:
https://github.com/urbanindo/yii2-queue/blob/master/src/Queue.php#L123

I would add a comment that the default value = 0 meaning no delay in the loop. Otherwise I support having this - I never let the loop go without delay.

**Comment by madeadi** [comment]
What I meant was, in the README.md, the previous version shows that `waitSecondsIfNoQueue` is configured at `UrbanIndo\Yii2\Queue\Console\Controller`. 

However, `waitSecondsIfNoQueue` is supposed to be configured at the component, i.e. `UrbanIndo\Yii2\Queue\Queues\DbQueue`

**Comment by TonisOrmisson** [comment]
ah, Yes :)

**Comment by petrabarus** [comment]
Thanks a lot for the input!

**Pull request merged**
